[project]
name = "aoc-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "marimo>=0.18.1",
    "numpy>=2.3.5",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "ruff>=0.14.7",
]
